### ISSUE TITLE
Project does not correctly import into IntelliJ

### ISSUE THREAD

**Issue by joshlemer** [scala/scala-collection-contrib#64]
The project loads into IntelliJ, but then for some reason, IntelliJ cannot understand that the tests require JUnit as a dependency, so everything JUnit is marked in red. This is confirmed with multiple fresh imports of the project, across multiple users and OS's (at least on Mac and Linux).   
  
<img width="1018" alt="Screen Shot 2019-11-01 at 1 24 00 PM" src="https://user-images.githubusercontent.com/5122903/68046872-f2396b80-fcaa-11e9-931a-354baaaa31a4.png">

**Comment by pioorg** [comment]
I think it's caused by #51, so this ticked is a duplicate.

**Comment by SethTisue** [comment]
@joshlemer is the problem fixed now?

**Comment by joshlemer** [comment]
@SethTisue a fresh clone still doesn't work on my machines, I know @julienrf was having trouble as well, maybe he can try out again as well.

**Comment by julienrf** [comment]
Actually, this was fixed by #63. It seems that it is not a good idea to define a `CrossProject` in the root directory because sbt also defines a root project in this directory that aggregates the `CrossProject` modules.

**Comment by SethTisue** [comment]
There is some some further (but inconclusive) discussion on #63. I don't think it's established (though not disproven either) that we're doing anything wrong in this repo. I would be curious to know if the other modules (scala-xml, scala-parser-combinators, etc) have the same problem or not. Perhaps there's some general advice we could provide to IntellIJ users at the sbt-scala-module level. It would also be useful to know what manual steps are necessary in order to get a working project IntelliJ.

**Comment by SethTisue** [comment]
I wonder if #114 randomly/accidentally fixed this

**Comment by julienrf** [comment]
Maybe! If someone confirms that the project can now be imported we can close the issue.

**Comment by joshlemer** [comment]
I confirm that I still can't import this into IntelliJ 😭

**Comment by mcallisto** [comment]
I just wanted to report that I am using the latest IntelliJ IDEA 2021.3.1 (Ultimate) and the import worked just fine.
